### ISSUE TITLE
IE Gradient Filter Breaks Dropkick

### ISSUE THREAD

**Issue by jackmahoney** [Robdel12/DropKick#120]
Using MS gradient filters in IE8 breaks dropkick.

For instance this css:

``` css
  #content .dk_container,
  {
    filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa', EndColorStr='#f0f0f0');
  }
```
