### ISSUE TITLE
new feature request: Placeholder Selected?

### ISSUE THREAD

**Issue by jimiwhite1020** [Robdel12/DropKick#258]
If the dropkick element is showing a placeholder text ( a disabled <option> tag ), can the generated elements have a class saying "placeholder-selected"? Then it will be easy to style the placeholder of the dropkick.
Thanks,
![image](https://cloud.githubusercontent.com/assets/3283920/5282471/ac241de2-7b41-11e4-9b22-a1c9f5ca8f21.png)

**Comment by wwilsman** [comment]
We've added a very simple feature that will allow you to do this. Simply supply your option element with a class similar to how you would hide it from the list, except now you can target styles when it is the currently selected option.

For example, where you might've previously done

````html
<select>
    <option class="placeholder-option">Select Option</option>
    <option>Up</option>
    <option>Down</option>
</select>
````

and styled it to hide `.placeholder-option` like so

````css
.placeholder-option {
    display: none;
}
````

You can now, similarly, do this (and be a little more specific)

````css
.dk-option.placeholder-option {
    display: none;
}

.dk-selected.placeholder-option {
    color: #CCCCCC;
}
````
